version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
  apt_packages:
    - libsodium-dev
  jobs:
    post_system_dependencies:
      - curl -L -o libxeddsa.a https://github.com/Syndace/libxeddsa/releases/download/v2.0.1/libxeddsa-linux-amd64.a

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
