language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - PYNACL_VERSION=1.2.1 CFFI_VERSION=1.11.5 # Most recent versions on pip
  - PYNACL_VERSION=1.0.1 CFFI_VERSION=1.9.1  # Version in Debian 9's apt repositories

install:
  - cd ref10/
  - make
  - cd bin/
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)
  - cd ../../
  - pip install pynacl==$PYNACL_VERSION
  - pip install cffi==$CFFI_VERSION
  - pip install -r requirements.txt
  - python setup.py install

script: py.test
