os:
  - linux
  - osx

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - PYNACL_VERSION=1.2.1 CFFI_VERSION=1.11.5 # Most recent versions on pip
  - PYNACL_VERSION=1.0.1 CFFI_VERSION=1.9.1  # Version in Debian 9's apt repositories

install:
  - pip install pynacl==$PYNACL_VERSION
  - pip install cffi==$CFFI_VERSION
  - pip install pytest
  - python setup.py install

script: py.test
