matrix:
  include:
  - os: linux
    language: python
    python: "3.6"
    env: LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: linux
    language: python
    python: "3.6"
    env: LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories
  - os: linux
    language: python
    python: "3.7"
    env: LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: linux
    language: python
    python: "3.7"
    env: LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories
  - os: linux
    language: python
    python: "3.8"
    env: LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: linux
    language: python
    python: "3.8"
    env: LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories
  - os: linux
    language: python
    python: "pypy3"
    env: LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: linux
    language: python
    python: "pypy3"
    env: LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.6.9 LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.6.9 LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.7.5 LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.7.5 LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.8.2 LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.8.2 LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories
  - os: osx
    language: generic
    env: PYTHON_VERSION=pypy3.6-7.3.0 LIBNACL_VERSION=1.7.1 CFFI_VERSION=1.14.0 # Most recent versions on pip
  - os: osx
    language: generic
    env: PYTHON_VERSION=pypy3.6-7.3.0 LIBNACL_VERSION=1.6.1 CFFI_VERSION=1.12.2  # Version in Debian 10's apt repositories

before_install:
  - . .travis/before_install.sh

install:
  - pip install libnacl==$LIBNACL_VERSION
  - pip install cffi==$CFFI_VERSION
  - pip install pytest mypy pylint
  - python setup.py install

script:
  - MYPYPATH=stubs mypy --show-error-codes xeddsa/
  - pylint xeddsa/
  - pytest
