jobs:
  include:
  - os: linux
    dist: focal
    language: python
    python: "3.7"
  - os: linux
    dist: focal
    language: python
    python: "3.7"
    env: DEBIAN_DEPS=true
  - os: linux
    dist: focal
    language: python
    python: "3.8"
  - os: linux
    dist: focal
    language: python
    python: "3.8"
    env: DEBIAN_DEPS=true
  - os: linux
    dist: focal
    language: python
    python: "3.9"
  - os: linux
    dist: focal
    language: python
    python: "3.9"
    env: DEBIAN_DEPS=true
  - os: linux
    dist: focal
    language: python
    python: "3.10"
  - os: linux
    dist: focal
    language: python
    python: "3.10"
    env: DEBIAN_DEPS=true
  - os: linux
    dist: focal
    language: python
    python: "pypy3"
  - os: linux
    dist: focal
    language: python
    python: "pypy3"
    env: DEBIAN_DEPS=true
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.7 DEBIAN_DEPS=true
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.8
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.8 DEBIAN_DEPS=true
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.9
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.9 DEBIAN_DEPS=true
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.10
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.10 DEBIAN_DEPS=true
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=pypy3
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=pypy3 DEBIAN_DEPS=true
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.7
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.7 DEBIAN_DEPS=true
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.8
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.8 DEBIAN_DEPS=true
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.9
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.9 DEBIAN_DEPS=true
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.10
  - os: windows
    language: bash
    env: TRAVIS_PYTHON_VERSION=3.10 DEBIAN_DEPS=true

addons:
  apt:
    packages:
    - libsodium23
    - libsodium-dev
  homebrew:
    packages:
    - pyenv
    - pyenv-virtualenv
    - libsodium
    update: true

before_install:
- source ${TRAVIS_BUILD_DIR}/.travis/before_install.sh

install:
- source ${TRAVIS_BUILD_DIR}/.travis/install.sh

script:
- source ${TRAVIS_BUILD_DIR}/.travis/script.sh
